export const GET_BEERS = 'GET_BEERS';

export const OPEN_BEER_MODAL = 'OPEN_BEER_MODAL';
export const OPEN_EDIT_BEER_MODAL = 'OPEN_EDIT_BEER_MODAL';
export const FETCH_BEERS_BEGIN = 'FETCH_BEERS_BEGIN';
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';
export const FETCH_BEERS_FAILURE = 'FETCH_BEERS_FAILURE';
